# Site settings
title: Nicholas T. Willis
description: None
baseurl: "/nicholastwillis" # the subpath of your site, e.g. /blog
url: "https://simplywillis.github.io"

# User settings
username: Nicholas T. Willis
user_description: expertise description
user_title: Researcher | Political Scientist | Social Scientist
email: ntwillis15@gmail.com
#twitter_username: lorem_ipsum
github_username:  SimplyWillis
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
